import sys
def replace_in_file(filepath, old_text, new_text):
    with open(filepath, 'r') as f:
        content = f.read()
    if old_text in content:
        content = content.replace(old_text, new_text)
        with open(filepath, 'w') as f:
            f.write(content)
        print(f"Updated {filepath}")
    else:
        print(f"Could not find old_text in {filepath}")

replace_in_file(
    "src/abersetz/__init__.py", 
    '"""Public package surface for abersetz."""',
    '"""Public package surface for abersetz.\n\nAbersetz is an AI-powered translation pipeline designed to be fast, reliable, and invisible.\nIt chunks text, hands it to language models, and stitches the translated pieces back together\nwithout breaking formatting or structure.\n\nWe export only what you need to run translations or handle their failures:\n- `translate_path`: The main workhorse for files and directories.\n- `TranslatorOptions`: Knobs and dials for the translation pipeline.\n- `TranslationResult`: The outcome, good or bad.\n- `PipelineError`: When things break, this tells you why.\n"""'
)

replace_in_file(
    "src/abersetz/__about__.py",
    "# file generated by setuptools-scm",
    "# file generated by setuptools-scm\n# Abersetz version information.\n# This file is automatically stamped during the build process."
)
