# Jekyll configuration for abersetz documentation
# Using just-the-docs theme

title: abersetz
description: Minimalist file translator with pluggable engines
baseurl: "/abersetz"
url: "https://twardoch.github.io"

# Theme configuration
remote_theme: just-the-docs/just-the-docs@v0.7.0
color_scheme: light

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Enable navigation
nav_enabled: true
nav_sort: case_sensitive

# Footer
footer_content: "Copyright &copy; 2025 Adam Twardoch. Distributed under the MIT License."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# External links
aux_links:
  "GitHub":
    - "https://github.com/twardoch/abersetz"
  "PyPI":
    - "https://pypi.org/project/abersetz"

# Collections for organizing content
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_xclude: false
      search_xclude: false

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# xclude files
xclude:
  - "*.py"
  - "*.sh"
  - "requirements.txt"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules/"
  - "vendor/"